### ISSUE TITLE
Add trading fees

### ISSUE THREAD

**Issue by egelja** [northwesternfintech/NUTC#107]
Otherwise you can just trade with yourself. CC: @echavemann 

I say we go with something like 0.04%, which is what Binance uses IIRC.

**Comment by stevenewald** [comment]
No. Bots are stochastic, this will heavily discourage riskier trades, which is not something we want to do.

PnL could easily become a game of "who placed the least orders". I prefer to have a zero sum game.

Reopen if you heavily disagree. CC @echavemann

**Comment by echavemann** [comment]
You need giga low fees to allow true HFT strategies. I think I agree with @stevenewald on this, we can tune in the future if order load becomes an issue. 

It could also be a multiple case situation - one case could have 0 fees, another could have standard fees. Does not need to be super high priority though.
