### ISSUE TITLE
Add market orders (vs limit)

### ISSUE THREAD

**Issue by stevenewald** [northwesternfintech/NUTC#145]
This is actually much easier than it sounds. Right now, orders are matched by limit and the price defaults to the passive order (the one the exchange received first). This will usually be MM prices

For example, say we have BUY=10 SELL=12 as the spread. If you submit a SELL order for 2, it'll default to price=10. If you submit a BUY order for 30, it'll default to 12.

This means we can make a market order by just setting the price to MAX/MIN_DOUBLE.

This will involve changes mostly(entirely?) to the wrapper. You may assume there are always open bids and asks in the exchange.

@echavemann Should we support market orders by dollar amount, or is share amount fine?

**Comment by echavemann** [comment]
I'm in favor of share only but I think both is probably the best option
