### ISSUE TITLE
Make firebase function to expose database to NUTC, allowing for better authentication

### ISSUE THREAD

**Issue by stevenewald** [northwesternfintech/NUTC#39]
- [ ] Make firebase function that provides entire database on call (sounds bad but necessary b/c each user spawned in to exchange)
- [ ] Make it so the firebase function requires a password parameter. This should check against firebase secrets (NOT anything hardcoded)
- [ ] Update NUTC to provide the password in the request from an environment variable
- [ ] Update NUTC to receive and process the database as usual from the function
- [ ] Add normal authorization to NUTC WEB

**Comment by egelja** [comment]
lgtm

**Comment by echavemann** [comment]
password sounds fine, which db are we dropping? jus the market data?

**Comment by stevenewald** [comment]
Irrelevant as planning to change to dynamodb/s3 before NUTC24
