### ISSUE TITLE
Randomize order of ObUpdates

### ISSUE THREAD

**Issue by stevenewald** [northwesternfintech/NUTC#49]
Right now, we iterate through wrappers in the client manager and send order book updates one-by-one. This gives an unfair advantage to the clients at the start of the iteration.

**Comment by echavemann** [comment]
https://en.cppreference.com/w/cpp/iterator/random_access_iterator

**Comment by echavemann** [comment]
1loc

**Comment by stevenewald** [comment]
Irrelevant now that we use rabbitmq exchanges
