### ISSUE TITLE
Create sandbox for algorithm testing

### ISSUE THREAD

**Issue by stevenewald** [northwesternfintech/NUTC#8]
Currently, the only way for users to test the implementation of their algorithms is to use the linter, which doesn't measure performance. We should create a sandbox for users to view how their algorithm interacts with the exchange during a simulated competition.

- [x] Determine correct architectural structure for sandbox/linter

Because each sandbox needs its **own** rabbitmq instance, we will make a program that spawns in an individual docker container for each sandboxed algorithm. This container will run the sandbox (`./NUTC --sandbox <algo_id>`), where <algo_id> is passed in to the docker container as an environment variable. After 10mins, NUTC sandbox exits and so does the docker container.

The program that spawns in docker containers will be written in go, and will receive requests via a server (main event loop for the program).

- [x] Implement sandbox in NUTC
- [x] Dockerize NUTC sandbox
- [x] Create program to spawn in NUTC sandbox containers
- [ ] Implement sandbox on web site
- [ ] Implement viewing metrics based on logged information (#2 )

**Comment by egelja** [comment]
Will the docker container also be running RabbitMQ?

**Comment by wry0313** [comment]
@egelja Steve said yes to that. Every docker container will have its own RabbitMQ

**Comment by egelja** [comment]
So you'll be running two processes in each docker container? Seems like a bad idea. Shouldn't you be using docker compose for that instead?

**Comment by echavemann** [comment]
I am fine with multiple RMQ instances here.

**Comment by echavemann** [comment]
What the planned frequency? UChicago did Cron

**Comment by echavemann** [comment]
Is there a reason we are dispatching with Go? Or just wanna get it done quickly?

**Comment by echavemann** [comment]
Also, is the plan to dispatch all of our systems at the same time with theirs? Or have some variance in market conditions?

**Comment by stevenewald** [comment]
> What the planned frequency? UChicago did Cron
Wdym frequency? Like rate limiting for people?

> Is there a reason we are dispatching with Go? Or just wanna get it done quickly?
Go is nice.

> Also, is the plan to dispatch all of our systems at the same time with theirs? Or have some variance in market conditions?
Wdym all our systems

**Comment by stevenewald** [comment]
> So you'll be running two processes in each docker container? Seems like a bad idea. Shouldn't you be using docker compose for that instead?

Why is this a bad idea? Considering we need a 1:1 mapping of rabbitmq to nutc-sandbox processes, I don't see how spinning up 2 containers for each instance of NUTC-sandbox is much better

**Comment by egelja** [comment]
> > Is there a reason we are dispatching with Go? Or just wanna get it done quickly?
> 
> Go is nice.

Wut. Have you SEEN the syntax???

> > So you'll be running two processes in each docker container? Seems like a bad idea. Shouldn't you be using docker compose for that instead?
> 
> Why is this a bad idea? Considering we need a 1:1 mapping of rabbitmq to nutc-sandbox processes, I don't see how spinning up 2 containers for each instance of NUTC-sandbox is much better

Ya ig this is fine. Just make sure RMQ is up and ready before running sandbox

**Comment by stevenewald** [comment]
> Wut. Have you SEEN the syntax???
Aint no way this is coming from a cpp dev

> Ya ig this is fine. Just make sure RMQ is up and ready before running sandbox

Yep

**Comment by egelja** [comment]
> Aint no way this is coming from a cpp dev

it just like doesn't have enough parens

like this code feels wrong

```go
    for _, a := range albums {
        if a.ID == id {
            c.IndentedJSON(http.StatusOK, a)
            return
        }
    }
```

**Comment by stevenewald** [comment]
Disagree, if you did the same in C++ it'd be twice as long and 50% less readable
