### ISSUE TITLE
True C++ support in exchange

### ISSUE THREAD

**Issue by egelja** [northwesternfintech/NUTC#99]
So this isn't that hard actually. We just need to tell our users to upload a *statically linked* `so` library. Then we don't even have to worry about `libc` or `libstdc++` differences. We just `dlopen` and call the functions we want.

I will take this issue. Goal is to get it done by the "dress rehearsal" run of NUTC. We sorta have support with #97 and #98 (but its very jank, either going `cpp -> py -> cpp` or requiring an `execv` call, respectively).

What needs to be done to get this working is:
- [ ] Add algo type info to firebase (@stevenewald you'll need to help me with that one)
- [ ] Make the wrapper aware of different algo types
- [ ] Add code to wrapper to `dlopen` a shared object and run its methods
- [ ] Add code to linter to check for expected functions in the shared object and test if they work
- [ ] Provide sample C++ project

The API with consist of four functions:
- `set_order_callback`
- `on_trade_update`
- `on_orderbook_update`
- `on_account_update`

The first one just allows us to tell the users' code what function they need to call too place an order. We will provide this for them.

**Comment by stevenewald** [comment]
Shelved for now unless @egelja wants to implement this e2e - can't spare bandwidth on the rest of the team

**Comment by egelja** [comment]
I'll do it - no ETA though.

**Comment by echavemann** [comment]
lol
